package gui;

import interestcomputation.InterestComputation;
import javafx.application.*;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.*;
import javafx.scene.control.*;
import javafx.stage.*;
import javafx.scene.layout.*;
import javafx.geometry.*;

@SuppressWarnings("restriction")

/* 
 * GUI that displays interest tables ranging from 1 up to 25 years. 
 * The tables are generated by selecting the appropriate button and 
 * based on the principal, rate and years values provided. 
 * One table displays simple interest, the second compound interest, 
 * and the third a combination of simple and compound interest. 
 */
public class InterestTableGUI extends Application {
	private TextArea displayArea;
	private TextField principal, rate;
	private Slider horizontalSlider;
	private Button simpleInterest, compoundInterest, bothInterests;

	@Override
	public void start(Stage primaryStage) {
		int sceneWidth = 400, sceneHeight = 300;
		int verSpaceBetweenNodes = 8, horSpaceBetweenNodes = 8;
		int paneBorderTop = 20, paneBorderBottom = 20,
				paneBorderRight = 20, paneBorderLeft = 20;
		
		/* Setting pane properties */
		GridPane pane = new GridPane();
		pane.setHgap(horSpaceBetweenNodes);
		pane.setVgap(verSpaceBetweenNodes);
		pane.setPadding(new Insets(paneBorderTop, paneBorderBottom,
				paneBorderRight, paneBorderLeft));
		
		/* Adding GUI elements */
		// DISPLAY AREA & SCROLL PANE
		displayArea = new TextArea();
		displayArea.setEditable(false);
		displayArea.setWrapText(true);
		ScrollPane scrollPane = new ScrollPane(displayArea);
		scrollPane.setPrefSize(250, 150);
		pane.add(scrollPane, 0, 0, 9, 1);
		
		// PRINCIPAL LABEL & TEXT FIELD
		Label principalLabel = new Label("Principal: ");
		principal = new TextField();
		pane.add(principalLabel, 0, 1, 1, 1);
		pane.add(principal, 1, 1, 3, 1);
		
		// RATE LABEL & TEXT FIELD
		Label rateLabel = new Label("Rate (Percentage): ");
		rate = new TextField();
		pane.add(rateLabel, 4, 1, 2, 1);
		pane.add(rate, 6, 1, 3, 1);
		
		// YEARS LABEL & SLIDER
		Label numOfYearsLabel = new Label("Number of Years: ");
		horizontalSlider = new Slider();
		horizontalSlider.setMin(1);
		horizontalSlider.setMax(25);
		horizontalSlider.setValue(1);
		horizontalSlider.setMajorTickUnit(4);
		horizontalSlider.setShowTickMarks(true);
		horizontalSlider.setShowTickLabels(true);
		pane.add(numOfYearsLabel, 0, 2, 4, 1);
		pane.add(horizontalSlider, 5, 2, 4, 1);
		
		// SIMPLE INTEREST BUTTON
		simpleInterest = new Button("Simple Interest");
		pane.add(simpleInterest, 0, 3, 2, 1);
		simpleInterest.setOnAction(new simpleInterestHandler());
		
		// COMPOUND INTEREST BUTTON
		compoundInterest = new Button("Compound Interest");
		pane.add(compoundInterest, 2, 3, 5, 1);

		/*
		 * Using anonymous inner class to display compound interest
		 */
		compoundInterest.setOnAction(new EventHandler<ActionEvent>() {
			public void handle(ActionEvent e) {
				displayArea.setText("Principal: $" + String.format("%.2f", getPrincipal()) + 
						", Rate: " + String.format("%.1f", getRate()) + "\n" + "Year, Compound Interest Amount" + 
						InterestComputation.compoundInterestTable(getPrincipal(), getRate(), getYears()));
			}
		});
		
		// BOTH INTERESTS BUTTON
		bothInterests = new Button("Both Interests");
		pane.add(bothInterests, 6, 3, 4, 1);
		
		/*
		 * Using lambda expression to display both interests
		 */
		bothInterests.setOnAction(e -> {
			displayArea.setText("Principal: $" + String.format("%.2f", getPrincipal()) + 
					", Rate: " + String.format("%.1f", getRate()) + "\n" + 
					"Year, Simple Interest Amount, Compound Interest Amount" +
					InterestComputation.bothInterestsTable(getPrincipal(), getRate(), getYears()));
		});
		
		/* Display the stage */
		Scene scene = new Scene(pane, sceneWidth, sceneHeight);
		primaryStage.setTitle("Interest Table Calculator");
		primaryStage.setScene(scene);
		primaryStage.show();
	}
	
	/*
	 * Using non-anonymous inner class to display simple interest
	 */
	private class simpleInterestHandler implements EventHandler<ActionEvent> {
		@Override
		public void handle(ActionEvent e) {
			displayArea.setText("Principal: $" + String.format("%.2f", getPrincipal()) + 
					", Rate: " + String.format("%.1f", getRate()) + "\n" + "Year, Simple Interest Amount" +
					InterestComputation.simpleInterestTable(getPrincipal(), getRate(), getYears()));
		}
	}
	
	private double getPrincipal() {
		return Double.parseDouble(principal.getText());
	}
	
	private double getRate() {
		return Double.parseDouble(rate.getText());
	}
	
	private double getYears() {
		return horizontalSlider.getValue();
	}
	
	public static void main(String[] args) {
		Application.launch(args);
	}
}
